import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { Typography,Box } from '@mui/material'
import { Home}  from '@/components'
const inter = Inter({ subsets: ['latin'] })

export default function HomeStart() {
  return (
    <>
      <Head>
        <title>NIT KKR-RAC(ISRO)</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <main>
      <Box>
      <Home/>

      </Box>
    
     </main>
    </>
  )
}
